### ISSUE TITLE
COTD results aren't working anymore

### ISSUE THREAD

**Issue by bastiHST90** [SoWieMarkus/TrackmaniaCOTDApp#1]
Just like title says, I can't see any cotd results anymore. It seems to have stopped at the 26th of january 2023.

Also: sometimes when I click a player the app loads forever. Right now it works.

I'm using a Galaxy S21 Ultra with Android 13.

**Comment by SoWieMarkus** [comment]
Thanks for telling me! My Monitoring failed again :D the problem was that for some reason Nadeo decided to change the title of the of the cup from "Cup of the day <date>" to "COTD <date>

The second thing that it keep loading forever is something that I experienced myself yesterday. But I don't have any idea what the reason could be. Logs looked fine 🤔 I will have an eye on that :)

**Comment by bastiHST90** [comment]
Seems like to work again. Thank you, I'll close this issue. :)
